run:
  concurrency: 4
  timeout: 30m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs-use-default: true
  skip-files: []
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  decorder:
    dec-order:
      - const
      - var
      - type
      - func
  dogsled:
    max-blank-identifiers: 3
  errcheck:
    check-type-assertions: true
    check-blank: true
  errchkjson:
    report-no-exported: true
  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 5
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  gofumpt:
    extra-rules: true
  grouper:
    const-require-single-const: true
    import-require-single-import: true
    var-require-single-var: true
  misspell:
    locale: US
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
  unparam:
    check-exported: true
linters:
  disable-all: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  fast: false


issues:
  exclude-dirs:
    - mocks
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - revive
      text: "returns unexported type"
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
